version: "3"
services:
  mysql:
    container_name: mysql-5
    build: ./docker/mysql
    image: mysql-5:5.6
    ports:
    - "3306:3306"
    - "9090:9090"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
    - ./mysql/mysql_data:/var/lib/mysql
    - ./mysql/mysql_db.cnf:/etc/mysql/conf.d/mysql_db.cnf
    expose:
    - "3306"
    - "9090"
  java:
    container_name: java-5
    build: .
    image: java-5:test
    depends_on:
      - mysql
    links:
      - mysql
    environment:
       MYSQL_IP: 192.168.99.100
       MYSQL_PORT: 3306
       USERNAME: root
       MYSQL_ROOT_PASSWORD: 123456
       DBNAME: sakila